# coding: utf-8

COLLECTION_ALIVE = 'ALIVE'

SELECTION_COLOR_RGB = 'SELECTION_COLOR_RGB'

FLAG = 'FLAG'
FLAG_DE = 'FLAG_DE'
FLAG_USSR = 'FLAG_USSR'

SIDE = 'SIDE'
SIDE_ALLIES = 'SIDE_ALLIES'
SIDE_AXIS = 'SIDE_AXIS'

COUNTRY = 'COUNTRY'
COUNTRY_USSR = 'USSR'
COUNTRY_DE = 'DE'

COMBAT_MODE = 'COMBAT_MODE'
COMBAT_MODE_DEFEND = 'COMBAT_MODE_DEFEND'
COMBAT_MODE_HIDE = 'COMBAT_MODE_HIDE'

DE_COLOR = (0, 81, 211)
USSR_COLOR = (204, 0, 0)
