# coding: utf-8

COLLECTION_ALIVE = 'ALIVE'

FLAG = 'FLAG'
FLAG_DE = 'DE'
FLAG_URSS = 'URSS'

SIDE = 'SIDE'
COMBAT_MODE = 'COMBAT_MODE'
COMBAT_MODE_DEFENSE = 'COMBAT_MODE_DEFENSE'

DE_COLOR = (0, 81, 211)
URSS_COLOR = (204, 0, 0)
