use serde::{Deserialize, Serialize};

use strum_macros::Display;
use strum_macros::EnumIter;

#[derive(Debug, Hash, Copy, Serialize, Deserialize, Clone, EnumIter, Eq, PartialEq, Display)]
pub enum Sound {
    MauserRiffleFire1,
    MauserRiffleFire2,
    MauserRiffleFire3,
    MauserRiffleReload1,
    MauserRiffleReload2,
    MosinNagantFire1,
    MosinNagantFire2,
    MosinNagantFire3,
    MosinNagantFire4,
    MosinNagantFire5,
    MosinNagantReload1,
    MosinNagantReload2,
    MosinNagantReload3,
    MosinNagantReload4,
    BrenMark2x1,
    BrenMark2x2,
    BrenMark2x3,
    BrenMark2x4,
    BrenMark2x5,
    BrenMark2x6,
    BrenMark2x7,
    BrenMark2x8,
    BrenMark2x9,
    BrenMark2x10,
    BrenMark2x11,
    BrenMark2x12,
    BrenMark2x13,
    BrenMark2x14,
    BrenMark2x15,
    BrenMark2x16,
    Mg34x1,
    Mg34x2,
    Mg34x3,
    Mg34x4,
    Mg34x5,
    Mg34x6,
    Mg34x7,
    Mg34x8,
    Mg34x9,
    Mg34x10,
    Mg34x11,
    Mg34x12,
    Mg34x13,
    Mg34x14,
    Mg34x15,
    Mg34x16,
    CannonFire1,
    ReloadGeneric1,
    MaleScreaming1,
    MaleScreaming2,
    MaleScreaming3,
    MaleScreaming4,
    MaleScreaming5,
    MaleDie1,
    MaleDie2,
    MaleDie3,
    MaleDie4,
    MaleDie5,
    MaleDie6,
    MaleDie7,
    MaleDie8,
    MetalHit1,
    Bip1,
    Clac1,
    Clic1,
    DrumMultiHits,
    TrumpetLongHall,
    BulletMetalImpact1,
    BulletTrunkImpact1,
    BulletWallImpact1,
    BulletGroundImpact1,
}

impl Sound {
    pub fn file_path(&self) -> String {
        format!("/audio/{}.ogg", self)
    }
}
