name: 'Install dependencies'
description: 'Install project OS dependencies (according using Ubuntu)'
runs:
  using: "composite"
  steps:
    - run: sudo apt-get install -y libasound2-dev libfontconfig-dev libudev-dev libzmq3-dev
      shell: bash
