[package]
name = "oc_core"
version = "0.2.0"
authors = ["Sevajol Bastien <contact@bux.fr>"]
edition = "2021"

[dependencies]
dirs = "4.0.0"
anyhow = "1.0.69"
thiserror = "1.0.39"
serde = { version = "1", features = ["derive"] }
