use super::{UI_SPRITE_SHEET_HEIGHT, UI_SPRITE_SHEET_WIDTH};

pub const SQUAD_TYPE1_START_X: f32 = 0.;
pub const SQUAD_TYPE1_START_Y: f32 = 700.;
pub const SQUAD_TYPE_WIDTH: f32 = 50.;
pub const SQUAD_TYPE_HEIGHT: f32 = 50.;

pub const SQUAD_REL_TYPE1_START_X: f32 = SQUAD_TYPE1_START_X / UI_SPRITE_SHEET_WIDTH;
pub const SQUAD_REL_TYPE1_START_Y: f32 = SQUAD_TYPE1_START_Y / UI_SPRITE_SHEET_HEIGHT;
pub const SQUAD_REL_TYPE1_WIDTH: f32 = SQUAD_TYPE_WIDTH / UI_SPRITE_SHEET_WIDTH;
pub const SQUAD_REL_TYPE1_HEIGHT: f32 = SQUAD_TYPE_HEIGHT / UI_SPRITE_SHEET_HEIGHT;
