use super::{UI_SPRITE_SHEET_HEIGHT, UI_SPRITE_SHEET_WIDTH};

pub const SQUAD_TYPE1_START_X: f32 = 0.;
pub const SQUAD_TYPE1_START_Y: f32 = 700.;
pub const SQUAD_TYPE_BREN_START_X: f32 = 0. + SQUAD_TYPE_WIDTH * 1.;
pub const SQUAD_TYPE_BREN_START_Y: f32 = 700.;
pub const SQUAD_TYPE_MG34_START_X: f32 = 0. + SQUAD_TYPE_WIDTH * 2.;
pub const SQUAD_TYPE_MG34_START_Y: f32 = 700.;
pub const SQUAD_TYPE_WIDTH: f32 = 50.;
pub const SQUAD_TYPE_HEIGHT: f32 = 50.;

pub const SQUAD_REL_TYPE1_START_X: f32 = SQUAD_TYPE1_START_X / UI_SPRITE_SHEET_WIDTH;
pub const SQUAD_REL_TYPE1_START_Y: f32 = SQUAD_TYPE1_START_Y / UI_SPRITE_SHEET_HEIGHT;
pub const SQUAD_REL_TYPE1_WIDTH: f32 = SQUAD_TYPE_WIDTH / UI_SPRITE_SHEET_WIDTH;
pub const SQUAD_REL_TYPE1_HEIGHT: f32 = SQUAD_TYPE_HEIGHT / UI_SPRITE_SHEET_HEIGHT;
pub const SQUAD_REL_TYPE_BREN_START_X: f32 = SQUAD_TYPE_BREN_START_X / UI_SPRITE_SHEET_WIDTH;
pub const SQUAD_REL_TYPE_BREN_START_Y: f32 = SQUAD_TYPE_BREN_START_Y / UI_SPRITE_SHEET_HEIGHT;
pub const SQUAD_REL_TYPE_BREN_WIDTH: f32 = SQUAD_TYPE_WIDTH / UI_SPRITE_SHEET_WIDTH;
pub const SQUAD_REL_TYPE_BREN_HEIGHT: f32 = SQUAD_TYPE_HEIGHT / UI_SPRITE_SHEET_HEIGHT;
pub const SQUAD_REL_TYPE_MG34_START_X: f32 = SQUAD_TYPE_MG34_START_X / UI_SPRITE_SHEET_WIDTH;
pub const SQUAD_REL_TYPE_MG34_START_Y: f32 = SQUAD_TYPE_MG34_START_Y / UI_SPRITE_SHEET_HEIGHT;
pub const SQUAD_REL_TYPE_MG34_WIDTH: f32 = SQUAD_TYPE_WIDTH / UI_SPRITE_SHEET_WIDTH;
pub const SQUAD_REL_TYPE_MG34_HEIGHT: f32 = SQUAD_TYPE_HEIGHT / UI_SPRITE_SHEET_HEIGHT;

pub const SOLDIER_1_START_X: f32 = 0.;
pub const SOLDIER_1_START_Y: f32 = 660.;
pub const SOLDIER_BREN_START_X: f32 = 0. + SOLDIER_WIDTH * 1.;
pub const SOLDIER_BREN_START_Y: f32 = 660.;
pub const SOLDIER_MG34_START_X: f32 = 0. + SOLDIER_WIDTH * 2.;
pub const SOLDIER_MG34_START_Y: f32 = 660.;
pub const SOLDIER_WIDTH: f32 = 20.;
pub const SOLDIER_HEIGHT: f32 = 20.;

pub const SOLDIER_REL_1_START_X: f32 = SOLDIER_1_START_X / UI_SPRITE_SHEET_WIDTH;
pub const SOLDIER_REL_1_START_Y: f32 = SOLDIER_1_START_Y / UI_SPRITE_SHEET_HEIGHT;
pub const SOLDIER_REL_BREN_START_X: f32 = SOLDIER_BREN_START_X / UI_SPRITE_SHEET_WIDTH;
pub const SOLDIER_REL_BREN_START_Y: f32 = SOLDIER_BREN_START_Y / UI_SPRITE_SHEET_HEIGHT;
pub const SOLDIER_REL_MG34_START_X: f32 = SOLDIER_MG34_START_X / UI_SPRITE_SHEET_WIDTH;
pub const SOLDIER_REL_MG34_START_Y: f32 = SOLDIER_MG34_START_Y / UI_SPRITE_SHEET_HEIGHT;
pub const SOLDIER_REL_WIDTH: f32 = SOLDIER_WIDTH / UI_SPRITE_SHEET_WIDTH;
pub const SOLDIER_REL_HEIGHT: f32 = SOLDIER_HEIGHT / UI_SPRITE_SHEET_HEIGHT;
